"""empty message

Revision ID: 10135ad12294
Revises: 
Create Date: 2018-01-23 16:39:42.792999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10135ad12294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CHECK',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('Add_Check', sa.Boolean(), nullable=False),
    sa.Column('Add_Event', sa.String(length=64), nullable=True),
    sa.Column('Add_Time', sa.String(length=64), nullable=True),
    sa.Column('Add_Index', sa.Integer(), nullable=True),
    sa.Column('Change_Check', sa.Boolean(), nullable=False),
    sa.Column('Change_Event', sa.String(length=64), nullable=True),
    sa.Column('Change_Type', sa.String(length=64), nullable=True),
    sa.Column('Change_Index', sa.Integer(), nullable=True),
    sa.Column('Delete_Event', sa.String(length=64), nullable=True),
    sa.Column('cookie', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('time', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Data')
    op.drop_table('CHECK')
    # ### end Alembic commands ###
