"""empty message

Revision ID: 14ba3d8c22fd
Revises: 36497d524c6d
Create Date: 2018-03-07 15:23:30.218698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14ba3d8c22fd'
down_revision = '36497d524c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER_DATA', 'PWD')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER_DATA', sa.Column('PWD', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
