"""empty message

Revision ID: 1ca5059f33dd
Revises: 220ecea93e9c
Create Date: 2018-06-25 18:10:48.926905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ca5059f33dd'
down_revision = '220ecea93e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Name', sa.String(length=16), nullable=True),
    sa.Column('Year', sa.Integer(), nullable=True),
    sa.Column('Time', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('Cource', 'Time',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cource', 'Time',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_table('Calendar')
    # ### end Alembic commands ###
