"""empty message

Revision ID: 1f713243ebd9
Revises: da5aa81eb2d5
Create Date: 2018-03-13 20:54:47.991422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f713243ebd9'
down_revision = 'da5aa81eb2d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cource_Data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cource_Data',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Cource_Data_id_seq"\'::regclass)'), nullable=False),
    sa.Column('Cource_Number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Cource_Teacher', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Cource_Name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Cource_Time', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('Cource_Week', sa.VARCHAR(length=16), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Cource_Data_pkey')
    )
    # ### end Alembic commands ###
