"""empty message

Revision ID: 20d799d625d6
Revises: ddd15fafc419
Create Date: 2018-03-10 02:34:08.269786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d799d625d6'
down_revision = 'ddd15fafc419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cource_Data', sa.Column('Cource_Week', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cource_Data', 'Cource_Week')
    # ### end Alembic commands ###
