"""empty message

Revision ID: 220ecea93e9c
Revises: 1f713243ebd9
Create Date: 2018-03-16 00:55:21.945526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '220ecea93e9c'
down_revision = '1f713243ebd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notebook', sa.Column('WhenRemind', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notebook', 'WhenRemind')
    # ### end Alembic commands ###
