"""empty message

Revision ID: 2e7b6bb5f011
Revises: 80da9f388bca
Create Date: 2018-02-02 20:45:39.039510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e7b6bb5f011'
down_revision = '80da9f388bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Apple_Realtime_News',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TITLE', sa.String(length=64), nullable=True),
    sa.Column('DATE', sa.String(length=64), nullable=True),
    sa.Column('URL', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('NEWS')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NEWS',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"NEWS_id_seq"\'::regclass)'), nullable=False),
    sa.Column('TITLE', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('DATE', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('URL', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'NEWS_pkey')
    )
    op.drop_table('Apple_Realtime_News')
    # ### end Alembic commands ###
