"""empty message

Revision ID: 3e45b827f042
Revises: b660ecf89b84
Create Date: 2018-01-24 17:37:10.016573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e45b827f042'
down_revision = 'b660ecf89b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER_DATA', sa.Column('PWD', sa.String(length=64), nullable=True))
    op.add_column('USER_DATA', sa.Column('Student_ID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER_DATA', 'Student_ID')
    op.drop_column('USER_DATA', 'PWD')
    # ### end Alembic commands ###
