"""empty message

Revision ID: 4f56f0bb197e
Revises: 20d799d625d6
Create Date: 2018-03-12 15:40:36.102985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f56f0bb197e'
down_revision = '20d799d625d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER_DATA', sa.Column('LastCource', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER_DATA', 'LastCource')
    # ### end Alembic commands ###
