"""empty message

Revision ID: 522bd2a9b9a7
Revises: 1ca5059f33dd
Create Date: 2018-06-25 19:08:39.471702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '522bd2a9b9a7'
down_revision = '1ca5059f33dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calendar', sa.Column('Day', sa.String(length=8), nullable=True))
    op.add_column('Calendar', sa.Column('Month', sa.String(length=8), nullable=True))
    op.drop_column('Calendar', 'Time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Calendar', sa.Column('Time', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.drop_column('Calendar', 'Month')
    op.drop_column('Calendar', 'Day')
    # ### end Alembic commands ###
