"""empty message

Revision ID: 56549ff0b995
Revises: 80c645b875b1
Create Date: 2018-02-16 00:10:29.111500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56549ff0b995'
down_revision = '80c645b875b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Weather_Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Humidity', sa.String(length=8), nullable=True),
    sa.Column('Temprature', sa.String(length=8), nullable=True),
    sa.Column('Feel_Temprature', sa.String(length=8), nullable=True),
    sa.Column('Railfall_Random', sa.String(length=8), nullable=True),
    sa.Column('Weather_Status', sa.String(length=16), nullable=True),
    sa.Column('Time', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column(u'Cource_Data', 'Cource_Credit')
    op.drop_column(u'Cource_Data', 'Cource_Classroom')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Cource_Data', sa.Column('Cource_Classroom', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    op.add_column(u'Cource_Data', sa.Column('Cource_Credit', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('Weather_Data')
    # ### end Alembic commands ###
