"""empty message

Revision ID: 6453205b32d1
Revises: aa90d64b9d5c
Create Date: 2018-03-02 16:36:39.566746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6453205b32d1'
down_revision = 'aa90d64b9d5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cource_Data', sa.Column('Cource_Week', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cource_Data', 'Cource_Week')
    # ### end Alembic commands ###
