"""empty message

Revision ID: 6557f63170d3
Revises: 8bb7b6ec28e0
Create Date: 2018-01-25 19:21:53.584096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6557f63170d3'
down_revision = '8bb7b6ec28e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Elective_Data', sa.Column('Number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Elective_Data', 'Number')
    # ### end Alembic commands ###
