"""empty message

Revision ID: 693e6c0c44e8
Revises: 14ba3d8c22fd
Create Date: 2018-03-10 00:36:27.492203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '693e6c0c44e8'
down_revision = '14ba3d8c22fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cource_Data', sa.Column('Cource_Week', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cource_Data', 'Cource_Week')
    # ### end Alembic commands ###
