"""empty message

Revision ID: 80c645b875b1
Revises: 2e7b6bb5f011
Create Date: 2018-02-03 13:41:46.020736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c645b875b1'
down_revision = '2e7b6bb5f011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Apple_Realtime_News', sa.Column('IMAGE_URL', sa.String(length=128), nullable=True))
    op.add_column('Apple_Realtime_News', sa.Column('NEWS_Type', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Apple_Realtime_News', 'NEWS_Type')
    op.drop_column('Apple_Realtime_News', 'IMAGE_URL')
    # ### end Alembic commands ###
