"""empty message

Revision ID: 80da9f388bca
Revises: 6557f63170d3
Create Date: 2018-01-26 14:58:00.357936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80da9f388bca'
down_revision = '6557f63170d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cource_Data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Cource_Number', sa.Integer(), nullable=True),
    sa.Column('Cource_Teacher', sa.String(length=64), nullable=True),
    sa.Column('Cource_Name', sa.String(length=64), nullable=True),
    sa.Column('Cource_Time', sa.String(length=64), nullable=True),
    sa.Column('Cource_Credit', sa.Integer(), nullable=True),
    sa.Column('Cource_Classroom', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cource_Data')
    # ### end Alembic commands ###
