"""empty message

Revision ID: 84f6362ce639
Revises: 88afdbbb8db8
Create Date: 2018-02-26 22:30:33.535303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f6362ce639'
down_revision = '88afdbbb8db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cource_Data', 'x')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cource_Data', sa.Column('x', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
