"""empty message

Revision ID: aa90d64b9d5c
Revises: 84f6362ce639
Create Date: 2018-02-26 23:17:09.121875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa90d64b9d5c'
down_revision = '84f6362ce639'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cource_Data', 'Cource_Time',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Cource_Data', 'Cource_Time',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    # ### end Alembic commands ###
