"""empty message

Revision ID: b660ecf89b84
Revises: 10135ad12294
Create Date: 2018-01-23 17:03:46.808101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b660ecf89b84'
down_revision = '10135ad12294'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('NEWS',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TITLE', sa.String(length=64), nullable=True),
    sa.Column('DATE', sa.String(length=64), nullable=True),
    sa.Column('URL', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Notebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('USER_ID', sa.String(length=64), nullable=True),
    sa.Column('Event', sa.String(length=64), nullable=True),
    sa.Column('Time', sa.String(length=64), nullable=True),
    sa.Column('Description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('USER_DATA',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('LINE_ID', sa.String(length=64), nullable=True),
    sa.Column('Add_Event', sa.String(length=64), nullable=True),
    sa.Column('Add_Time', sa.String(length=64), nullable=True),
    sa.Column('Add_Index', sa.Integer(), nullable=True),
    sa.Column('Change_Event', sa.String(length=64), nullable=True),
    sa.Column('Change_Type', sa.String(length=64), nullable=True),
    sa.Column('Change_Index', sa.Integer(), nullable=True),
    sa.Column('Delete_Event', sa.String(length=64), nullable=True),
    sa.Column('Curriculum_Cookie', sa.String(length=64), nullable=True),
    sa.Column('Status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Data')
    op.drop_table('CHECK')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CHECK',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"CHECK_id_seq"\'::regclass)'), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Add_Check', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Add_Event', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Add_Time', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Add_Index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Change_Check', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('Change_Event', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Change_Type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('Change_Index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Delete_Event', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('cookie', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'CHECK_pkey')
    )
    op.create_table('Data',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u'nextval(\'"Data_id_seq"\'::regclass)'), nullable=False),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('time', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'Data_pkey')
    )
    op.drop_table('USER_DATA')
    op.drop_table('Notebook')
    op.drop_table('NEWS')
    # ### end Alembic commands ###
