"""empty message

Revision ID: bcc6868a96cd
Revises: 56549ff0b995
Create Date: 2018-02-20 00:42:24.178187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc6868a96cd'
down_revision = '56549ff0b995'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tech_News',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TITLE', sa.String(length=64), nullable=True),
    sa.Column('URL', sa.String(length=128), nullable=True),
    sa.Column('IMAGE_URL', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tech_News')
    # ### end Alembic commands ###
