"""empty message

Revision ID: da5aa81eb2d5
Revises: 4f56f0bb197e
Create Date: 2018-03-13 00:13:38.577883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5aa81eb2d5'
down_revision = '4f56f0bb197e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cource',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Number', sa.Integer(), nullable=True),
    sa.Column('Teacher', sa.String(length=64), nullable=True),
    sa.Column('Name', sa.String(length=128), nullable=True),
    sa.Column('Time', sa.Text(), nullable=False),
    sa.Column('Week', sa.String(length=16), nullable=True),
    sa.Column('SourceTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cource')
    # ### end Alembic commands ###
