"""empty message

Revision ID: ddd15fafc419
Revises: 693e6c0c44e8
Create Date: 2018-03-10 02:33:15.814663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddd15fafc419'
down_revision = '693e6c0c44e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Cource_Data', 'Cource_Week')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cource_Data', sa.Column('Cource_Week', sa.VARCHAR(length=16), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
