"""empty message

Revision ID: e3f37e75ed3b
Revises: bcc6868a96cd
Create Date: 2018-02-22 00:01:12.390326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f37e75ed3b'
down_revision = 'bcc6868a96cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('USER_DATA', sa.Column('Remind', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('USER_DATA', 'Remind')
    # ### end Alembic commands ###
