"""empty message

Revision ID: ee0b47398a60
Revises: b0540f6cac85
Create Date: 2018-03-06 16:51:55.415569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee0b47398a60'
down_revision = 'b0540f6cac85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Notebook', sa.Column('RemindTime', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Notebook', 'RemindTime')
    # ### end Alembic commands ###
